# Generated by Django 4.0.9 on 2023-03-23 22:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_developed_formmodel_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 13, 17, 47, 879815, tzinfo=utc)),
        ),
    ]
